const allQuestions = {
    ofc: [
        { question: 'What is One Football\'s main mission?', options: ['To connect and reward football fans globally', 'To replace traditional football', 'To create expensive NFTs', 'To control football clubs'], correct: 0 },
        { question: 'One Football aims to give fans what kind of power?', options: ['No power', 'Only viewing rights', 'Administrative control', 'Ownership and voting rights'], correct: 3 },
        { question: 'What does One Football want to democratize?', options: ['Football player salaries', 'The football fan experience', 'Stadium ownership', 'Referee decisions'], correct: 1 },
        { question: 'One Football focuses on connecting which communities?', options: ['Only professional clubs', 'Only European fans', 'Global football fans and communities', 'Only wealthy supporters'], correct: 2 },
        { question: 'What is One Football\'s approach to fan engagement?', options: ['Traditional membership only', 'Pay-per-view model', 'Subscription-based access', 'Blockchain-powered community participation'], correct: 3 },
        { question: 'What is the primary utility of OFC tokens?', options: ['Fan rewards and governance participation', 'Pure speculation', 'Mining cryptocurrency', 'Buying expensive merchandise'], correct: 0 },
        { question: 'How can fans earn OFC tokens?', options: ['Only by purchasing', 'Through community engagement and activities', 'By owning football clubs', 'Through mining operations'], correct: 1 },
        { question: 'OFC tokens can be used for what purpose?', options: ['Only trading', 'Controlling player transfers', 'Voting on community decisions and accessing rewards', 'Setting ticket prices'], correct: 2 },
        { question: 'What makes OFC tokens valuable to fans?', options: ['High market price only', 'Government backing', 'Celebrity endorsements', 'Utility in the fan ecosystem and governance rights'], correct: 3 },
        { question: 'How does One Football ensure fair token distribution?', options: ['Merit-based rewards for fan engagement', 'Random giveaways', 'Only to wealthy investors', 'Through expensive purchases only'], correct: 0 },
        { question: 'One Football tokens can be used to access what?', options: ['Only basic content', 'Exclusive fan experiences and premium content', 'Stadium construction', 'Player contracts'], correct: 1 },
        { question: 'What type of content does One Football provide to token holders?', options: ['Basic news only', 'Only match highlights', 'Exclusive interviews, behind-the-scenes content, and fan experiences', 'Advertising content'], correct: 2 },
        { question: 'How does One Football support grassroots football?', options: ['It doesn\'t', 'Only professional focus', 'By charging high fees', 'Through community programs and token incentives'], correct: 3 },
        { question: 'One Football\'s platform allows fans to do what?', options: ['Participate in community governance and earn rewards', 'Only watch games', 'Control player decisions', 'Set match schedules'], correct: 0 },
        { question: 'What kind of experiences can OFC token holders access?', options: ['Standard experiences only', 'VIP events, exclusive content, and community perks', 'No special experiences', 'Only expensive packages'], correct: 1 },
        { question: 'One Football is building partnerships with which entities?', options: ['Only tech companies', 'Only cryptocurrency exchanges', 'Football clubs, leagues, and fan communities', 'Government agencies only'], correct: 2 },
        { question: 'What technology does One Football use to ensure transparency?', options: ['Traditional databases', 'Paper records', 'Email systems', 'Blockchain technology'], correct: 3 },
        { question: 'One Football\'s mobile app focuses on what?', options: ['User-friendly fan engagement and rewards', 'Complex trading only', 'Technical analysis', 'Professional use only'], correct: 0 },
        { question: 'How does One Football handle fan data and privacy?', options: ['Sells user data', 'Blockchain-secured privacy and user control', 'No privacy protection', 'Government surveillance'], correct: 1 },
        { question: 'One Football\'s community governance allows fans to vote on what?', options: ['Player transfers', 'Match results', 'Platform improvements and community initiatives', 'Referee decisions'], correct: 2 },
        { question: 'Which blockchain network does One Football primarily use?', options: ['Bitcoin', 'Ethereum', 'Solana', 'Polygon (Matic)'], correct: 3 },
        { question: 'What type of token standard does OFC likely use?', options: ['ERC-20', 'ERC-721', 'BEP-20', 'TRC-20'], correct: 0 },
        { question: 'One Football\'s smart contracts enable what functionality?', options: ['Only token transfers', 'Automated governance, rewards, and fan interactions', 'Mining operations', 'Price manipulation'], correct: 1 },
        { question: 'How does One Football ensure scalability?', options: ['Single server setup', 'No scaling strategy', 'Layer 2 solutions and optimized blockchain infrastructure', 'Centralized databases only'], correct: 2 },
        { question: 'What consensus mechanism benefits One Football\'s operations?', options: ['Proof of Work only', 'No consensus needed', 'Centralized validation', 'Proof of Stake for energy efficiency'], correct: 3 },
        { question: 'One Football\'s community includes which groups?', options: ['Fans, clubs, content creators, and football enthusiasts', 'Only professional players', 'Only wealthy investors', 'Only European supporters'], correct: 0 },
        { question: 'How can content creators benefit from One Football?', options: ['No benefits available', 'Token rewards for quality content and fan engagement', 'Only traditional payments', 'No creator support'], correct: 1 },
        { question: 'What role do fan clubs play in One Football\'s ecosystem?', options: ['No role', 'Only viewing content', 'Active community participation and governance', 'Administrative tasks only'], correct: 2 },
        { question: 'One Football supports which types of football?', options: ['Only professional leagues', 'Only European football', 'Only men\'s football', 'All levels from grassroots to professional'], correct: 3 },
        { question: 'How does One Football measure community success?', options: ['Fan engagement, community growth, and ecosystem value', 'Token price only', 'Number of downloads only', 'Revenue metrics only'], correct: 0 },
        { question: 'One Football\'s global strategy focuses on what?', options: ['Single country only', 'Worldwide football community building', 'Only English-speaking markets', 'Limited geographic reach'], correct: 1 },
        { question: 'What type of partnerships does One Football seek?', options: ['Only financial partnerships', 'No partnerships', 'Strategic football ecosystem collaborations', 'Only technology partnerships'], correct: 2 },
        { question: 'How does One Football support different languages?', options: ['English only', 'Limited language support', 'No localization', 'Multi-language platform for global accessibility'], correct: 3 },
        { question: 'One Football\'s approach to emerging markets is?', options: ['Inclusive growth and accessibility', 'Ignore emerging markets', 'High-cost entry only', 'Limited market focus'], correct: 0 },
        { question: 'What makes One Football different from traditional sports media?', options: ['Higher subscription costs', 'Fan ownership, blockchain rewards, and community governance', 'Less content available', 'More advertising'], correct: 1 },
        { question: 'One Football\'s innovation focus includes what areas?', options: ['No innovation plans', 'Only traditional methods', 'Fan technology, blockchain integration, and community tools', 'Limited tech adoption'], correct: 2 },
        { question: 'How does One Football plan to evolve?', options: ['Stay the same', 'Top-down control only', 'External company decisions', 'Community-driven development and continuous innovation'], correct: 3 },
        { question: 'What role does AI play in One Football\'s future?', options: ['Enhanced fan experiences and personalized content', 'No AI integration', 'Replace human interaction', 'Only for trading'], correct: 0 },
        { question: 'One Football\'s sustainability approach focuses on what?', options: ['High energy consumption', 'Eco-friendly blockchain practices and community value', 'No environmental concern', 'Traditional energy sources'], correct: 1 },
        { question: 'How does One Football plan to onboard new users?', options: ['Complex technical processes', 'No onboarding support', 'Simple, user-friendly experiences', 'Expert-level requirements only'], correct: 2 },
        { question: 'One Football is primarily a platform for whom?', options: ['Only players', 'Only coaches', 'Only referees', 'Football fans'], correct: 3 },
        { question: 'What does OFC stand for in One Football context?', options: ['One Football Coin', 'One Football Club', 'Official Football Chain', 'Open Football Community'], correct: 0 },
        { question: 'One Football uses blockchain to provide what benefit?', options: ['Slower transactions', 'Transparency and fan ownership', 'Higher costs', 'Less security'], correct: 1 },
        { question: 'Can fans influence One Football\'s development?', options: ['No influence allowed', 'Only wealthy fans', 'Yes, through community governance', 'Only professional input'], correct: 2 },
        { question: 'One Football\'s target audience is?', options: ['Limited to experts', 'Only cryptocurrency traders', 'Only professional clubs', 'All football fans globally'], correct: 3 },
        { question: 'One Football\'s token economy is designed to?', options: ['Reward active community participation', 'Benefit only founders', 'Exclude small fans', 'Focus on speculation'], correct: 0 },
        { question: 'How does One Football ensure community input?', options: ['No community input', 'Blockchain-based voting and proposals', 'Only surveys', 'Executive decisions only'], correct: 1 },
        { question: 'What makes One Football\'s approach unique?', options: ['Traditional centralized model', 'High-cost premium service', 'Decentralized fan-owned ecosystem', 'Limited access platform'], correct: 2 },
        { question: 'One Football\'s revenue sharing benefits whom?', options: ['Only the company', 'Only investors', 'Only partners', 'The entire community ecosystem'], correct: 3 },
        { question: 'How does One Football handle content moderation?', options: ['Community-driven standards and governance', 'No moderation', 'Strict censorship', 'External company control'], correct: 0 }
    ],
    football: [
        { question: 'Which country won the first FIFA World Cup in 1930?', options: ['Uruguay', 'Brazil', 'Argentina', 'Italy'], correct: 0 },
        { question: 'Who won the 2022 FIFA World Cup in Qatar?', options: ['France', 'Argentina', 'Brazil', 'Croatia'], correct: 1 },
        { question: 'Which country has won the most World Cups?', options: ['Germany', 'Argentina', 'Brazil', 'Italy'], correct: 2 },
        { question: 'Who scored the "Hand of God" goal in 1986?', options: ['Pelé', 'Lionel Messi', 'Ronaldinho', 'Diego Maradona'], correct: 3 },
        { question: 'Which player has scored the most World Cup goals ever?', options: ['Miroslav Klose', 'Pelé', 'Ronaldo', 'Gerd Müller'], correct: 0 },
        { question: 'Which player is known as "The King of Football"?', options: ['Maradona', 'Pelé', 'Messi', 'Ronaldo'], correct: 1 },
        { question: 'Cristiano Ronaldo is from which country?', options: ['Spain', 'Brazil', 'Portugal', 'Argentina'], correct: 2 },
        { question: 'Lionel Messi played most of his career at which club?', options: ['Real Madrid', 'PSG', 'Manchester City', 'Barcelona'], correct: 3 },
        { question: 'Which player is known as "CR7"?', options: ['Cristiano Ronaldo', 'Carlos Ronaldo', 'Clarence Ronaldinho', 'Cafu Roberto'], correct: 0 },
        { question: 'Who is known as "The Egyptian King"?', options: ['Mohamed Elneny', 'Mohamed Salah', 'Ahmed Hegazi', 'Mahmoud Trezeguet'], correct: 1 },
        { question: 'Which club is known as "The Red Devils"?', options: ['Liverpool', 'Arsenal', 'Manchester United', 'AC Milan'], correct: 2 },
        { question: 'Real Madrid\'s home stadium is called?', options: ['Camp Nou', 'Old Trafford', 'Anfield', 'Santiago Bernabéu'], correct: 3 },
        { question: 'Which club has won the most UEFA Champions League titles?', options: ['Real Madrid', 'Barcelona', 'AC Milan', 'Liverpool'], correct: 0 },
        { question: 'Arsenal is known by which nickname?', options: ['The Blues', 'The Gunners', 'The Red Devils', 'The Citizens'], correct: 1 },
        { question: 'Which Italian club is known as "The Old Lady"?', options: ['AC Milan', 'Inter Milan', 'Juventus', 'Roma'], correct: 2 },
        { question: 'Which team won the Premier League in the 2015-16 season?', options: ['Chelsea', 'Manchester City', 'Arsenal', 'Leicester City'], correct: 3 },
        { question: 'Who has scored the most goals in Premier League history?', options: ['Alan Shearer', 'Thierry Henry', 'Wayne Rooney', 'Harry Kane'], correct: 0 },
        { question: 'Manchester City\'s home ground is called?', options: ['Old Trafford', 'Etihad Stadium', 'Stamford Bridge', 'Emirates Stadium'], correct: 1 },
        { question: 'Which manager is known as "The Special One"?', options: ['Pep Guardiola', 'Arsène Wenger', 'José Mourinho', 'Sir Alex Ferguson'], correct: 2 },
        { question: 'Liverpool\'s famous anthem is?', options: ['Blue Moon', 'Glory Glory', 'Come On You Spurs', 'You\'ll Never Walk Alone'], correct: 3 },
        { question: 'Barcelona\'s home stadium is?', options: ['Camp Nou', 'Santiago Bernabéu', 'Wanda Metropolitano', 'Mestalla'], correct: 0 },
        { question: 'Which Spanish club is known as "Los Blancos"?', options: ['Barcelona', 'Real Madrid', 'Atletico Madrid', 'Valencia'], correct: 1 },
        { question: 'El Clásico is the match between which two teams?', options: ['Real Madrid vs Atletico', 'Barcelona vs Valencia', 'Real Madrid vs Barcelona', 'Sevilla vs Real Madrid'], correct: 2 },
        { question: 'Which player scored the most goals in La Liga history?', options: ['Cristiano Ronaldo', 'Raúl', 'Telmo Zarra', 'Lionel Messi'], correct: 3 },
        { question: 'Atletico Madrid\'s stadium is called?', options: ['Wanda Metropolitano', 'Santiago Bernabéu', 'Camp Nou', 'Mestalla'], correct: 0 },
        { question: 'Which Italian club is known as "The Rossoneri"?', options: ['Juventus', 'AC Milan', 'Inter Milan', 'Roma'], correct: 1 },
        { question: 'Bayern Munich plays in which league?', options: ['Premier League', 'La Liga', 'Bundesliga', 'Serie A'], correct: 2 },
        { question: 'Paris Saint-Germain is based in which country?', options: ['Spain', 'Italy', 'Germany', 'France'], correct: 3 },
        { question: 'Which club is known as "The Yellow Wall"?', options: ['Borussia Dortmund', 'Bayern Munich', 'RB Leipzig', 'Schalke'], correct: 0 },
        { question: 'Ajax is from which country?', options: ['Belgium', 'Netherlands', 'Denmark', 'Sweden'], correct: 1 },
        { question: 'Which country won Euro 2021?', options: ['England', 'Spain', 'Italy', 'France'], correct: 2 },
        { question: 'Copa América is the championship for which continent?', options: ['Europe', 'Africa', 'Asia', 'South America'], correct: 3 },
        { question: 'Which country has won the most European Championships?', options: ['Germany', 'Spain', 'Italy', 'France'], correct: 0 },
        { question: 'The African Cup of Nations is held every how many years?', options: ['2 years', '3 years', '4 years', '5 years'], correct: 0 },
        { question: 'Which country hosted the 2018 World Cup?', options: ['Brazil', 'Russia', 'Germany', 'South Africa'], correct: 1 },
        { question: 'How many players are on the field for each team?', options: ['10', '11', '12', '9'], correct: 1 },
        { question: 'What is the standard length of a football match?', options: ['80 minutes', '90 minutes', '100 minutes', '120 minutes'], correct: 1 },
        { question: 'What does VAR stand for?', options: ['Video Assistant Referee', 'Virtual Assistant Review', 'Video Analysis Report', 'Variable Action Replay'], correct: 0 },
        { question: 'How many substitutions are typically allowed in a match?', options: ['3', '5', '7', 'Unlimited'], correct: 1 },
        { question: 'What is the offside rule?', options: ['Player ahead of ball', 'Player in opponent half', 'Player ahead of second-last opponent when ball is played', 'Player touching the ball'], correct: 2 },
        { question: 'Which stadium is known as "The Theatre of Dreams"?', options: ['Wembley', 'Old Trafford', 'Anfield', 'Emirates'], correct: 1 },
        { question: 'Wembley Stadium is located in which city?', options: ['Manchester', 'Liverpool', 'London', 'Birmingham'], correct: 2 },
        { question: 'The Maracanã Stadium is in which country?', options: ['Argentina', 'Brazil', 'Colombia', 'Mexico'], correct: 1 },
        { question: 'Which stadium is known as "La Bombonera"?', options: ['River Plate', 'Boca Juniors', 'Racing Club', 'Independiente'], correct: 1 },
        { question: 'San Siro is the home of which clubs?', options: ['Juventus and Roma', 'AC Milan and Inter Milan', 'Lazio and Roma', 'Napoli and Atalanta'], correct: 1 },
        { question: 'Which country won the 2019 Women\'s World Cup?', options: ['England', 'Netherlands', 'United States', 'Germany'], correct: 2 },
        { question: 'Who is considered one of the greatest female footballers?', options: ['Marta', 'Megan Rapinoe', 'Alex Morgan', 'All of the above'], correct: 3 },
        { question: 'The Women\'s World Cup is held every how many years?', options: ['2 years', '3 years', '4 years', '5 years'], correct: 2 },
        { question: 'Which country has won the most Women\'s World Cups?', options: ['Germany', 'United States', 'Norway', 'Brazil'], correct: 1 },
        { question: 'The UEFA Women\'s Championship is also known as?', options: ['Women\'s Euro', 'European Cup', 'Continental Cup', 'Ladies Championship'], correct: 0 }
    ]
};